# Keep dependencies up to date with automated pull requests
#
# IMPORTANT: Dependency grouping was causing Dependabot to skip package-lock.json
# updates, leading to CI failures. Grouping disabled until root cause confirmed.
# See TODO.md "Fix Dependabot CI Failures" for investigation details.
#
# If you re-enable grouping, verify that Dependabot PRs include package-lock.json
# changes by checking the commit file list before merging.
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'UTC'
    # Raise all npm dependencies updates as a single PR
    # NOTE: Grouping temporarily disabled - was causing lockfile generation failures
    # groups:
    #   production-dependencies:
    #     dependency-type: 'production'
    #   development-dependencies:
    #     dependency-type: 'development'
    #     patterns:
    #       - '*'
    #     exclude-patterns:
    #       - '@types/*'
    #   types-dependencies:
    #     patterns:
    #       - '@types/*'
    # Limit number of open pull requests
    open-pull-requests-limit: 5
    # Always increase the minimum version requirement
    versioning-strategy: increase
    # Disable automerge for npm packages
    # (requires manual review due to potential breaking changes)
    commit-message:
      prefix: 'chore'
      include: 'scope'
    # Request review from repo owner
    reviewers:
      - 'phaedrus'
    # Add security label for vulnerability patches
    labels:
      - 'dependencies'
      - 'security'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    # Use semantic commit messages for GitHub Actions
    commit-message:
      prefix: 'ci'
      include: 'scope'
    # Actions are generally safer to update
    open-pull-requests-limit: 3
    # Add labels for GitHub Actions updates
    labels:
      - 'dependencies'
      - 'ci'
