/**
 * Quote type definitions
 *
 * Contains the interface and related types for the Quote entity.
 */

/**
 * Quote interface
 *
 * Represents a quote that can be displayed in the application.
 */
export interface Quote {
  /** Unique numeric identifier */
  id: number;

  /** The text content of the quote */
  text: string;

  /** The author of the quote, or null if anonymous/unknown */
  author: string | null;
}

/**
 * QuoteInput interface
 *
 * Used for creating or updating a quote. Omits the id which is
 * generated by the database.
 */
export interface QuoteInput {
  text: string;
  author?: string | null;
}
