/**
 * Reading type definitions
 * 
 * Contains the interface and related types for the Reading entity.
 */

/**
 * Reading interface
 * 
 * Represents a book or article that has been read or is currently being read.
 */
export interface Reading {
  /** Unique numeric identifier */
  id: number;
  
  /** URL-friendly unique identifier */
  slug: string;
  
  /** Title of the book or article */
  title: string;
  
  /** Author of the book or article */
  author: string;
  
  /** Date when the reading was completed, or null if still in progress
   * Note: This can be a Date object when used directly with Prisma models,
   * or a string when coming from API responses (especially with raw SQL queries)
   */
  finishedDate: Date | string | null;
  
  /** URL to the cover image, or null if not available */
  coverImageSrc: string | null;
  
  /** Thoughts or notes about the reading */
  thoughts: string;
  
  /** Indicates if the reading was abandoned before completion */
  dropped: boolean;
}

/**
 * ReadingInput interface
 * 
 * Used for creating or updating a reading. Makes certain fields optional
 * and omits the id which is generated by the database.
 */
export interface ReadingInput {
  slug: string;
  title: string;
  author: string;
  finishedDate?: Date | string | null;
  coverImageSrc?: string | null;
  thoughts?: string;
  dropped?: boolean;
}

/**
 * ReadingListItem interface
 * 
 * A simplified version of Reading used for list views.
 * Note: finishedDate can be a Date object or a string when coming from API responses
 */
export interface ReadingListItem {
  slug: string;
  title: string;
  author: string;
  finishedDate: Date | string | null;
  coverImageSrc: string | null;
  dropped: boolean;
}