#!/usr/bin/env node
// Regenerate quotes.js from the daybook quote collection.
//
// Source of truth: the numbered files (NNNN.md) in ~/Documents/daybook/Quotes,
// each with YAML frontmatter carrying a curated `author:` attribution. The
// unnumbered clipping files in the same directory are raw imports with
// unreliable attributions and are intentionally ignored.
//
// Rules:
// - only quotes that fit the colophon reserve (MAX_LEN chars; see the
//   .q-foot min-height note in index.html and AGENTS.md)
// - dedupe by normalized text
// - sort by attribution, then text
//
// Usage: node scripts/generate-quotes.mjs [daybook-quotes-dir]

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';

const MAX_LEN = 250;
const dir = process.argv[2] ?? join(homedir(), 'Documents', 'daybook', 'Quotes');
const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'quotes.js');

function parseQuoteFile(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return null;
  const authorLine = m[1].match(/^author:\s*(.*)$/m);
  if (!authorLine) return null;
  let author = authorLine[1].trim();
  if (author.startsWith("'") && author.endsWith("'")) {
    author = author.slice(1, -1).replace(/''/g, "'");
  } else if (author.startsWith('"') && author.endsWith('"')) {
    author = author.slice(1, -1).replace(/\\"/g, '"');
  }
  const body = m[2].replace(/\*\[\[[^\]]*\]\]\*/g, '').trim();
  if (!body || !author) return null;
  return [body, author];
}

const files = readdirSync(dir).filter((f) => /^\d+\.md$/.test(f)).sort();
const seen = new Map();
let skippedLong = 0;
for (const f of files) {
  const parsed = parseQuoteFile(readFileSync(join(dir, f), 'utf8'));
  if (!parsed) {
    console.warn(`skipping ${f}: no parseable author/body`);
    continue;
  }
  if (parsed[0].length > MAX_LEN) {
    skippedLong++;
    continue;
  }
  const key = parsed[0].toLowerCase().replace(/\s+/g, ' ');
  if (!seen.has(key)) seen.set(key, parsed);
}

const quotes = [...seen.values()].sort(
  (a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0])
);

const header = `/* the quotes: pulled from the daybook collection. The colophon footer
   reserves height for the longest quote in the pool (~${MAX_LEN} chars); if a
   longer one lands, bump the .q-foot min-height reserve in index.html.
   Generated by scripts/generate-quotes.mjs from ~/Documents/daybook/Quotes. */
`;
writeFileSync(outPath, `${header}window.QUOTES = ${JSON.stringify(quotes)};\n`);
console.log(
  `wrote ${quotes.length} quotes (${skippedLong} skipped over ${MAX_LEN} chars, ` +
    `${files.length - skippedLong - quotes.length} deduped/unparsed)`
);
